packages/dialog/Dialog.svelte

The MDC dialog component doesn't have a method named "isOpen()", it's actually a property.

Fixed Dialog isOpen

---

packages/textfield/Input.svelte

Fix for #40 
Solve the issue by maintaining setting `valueProps.value` to `''` when `value` is `undefined`, so MDCTextField can interact with it properly.

Handle undefined number input for textfield

---

packages/common/ClassAdder.svelte

When you try to `npm run dev` on an [webpack based sapper installation](https://github.com/manuel3108/sapper-smui-template) and add for example the drawer component, you will get the following **warning**:
```js
node_modules/@smui/common/ClassAdder.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
ClassAdder has unused export property 'internals'. If it is for external reference only, please consider using `export const 'internals'` (9:13)
7: 
8: <script context="module">
9:   export let internals = {
^
10:     component: null,
11:     smuiClass: null,
```
This occurs at least for the drawer and the data-tables component, but propably for every component who uses `ClassAdder.svelte`. This will be fixed width this PR

fix sapper compiler warning

---

packages/menu-surface/MenuSurface.svelte

This was a regression in beta18. Svelte calls onDestroy on the server, so we have to check that menuSurface is not undefined before calling destroy()

fix: Cannot read property 'destroy' of undefined in menuSurface

---

packages/textfield/Textfield.svelte

Textfield was not passing the step min and max props to the assosciated <Input> resulting in no availability of base HTML5 functions.
Closes #115

Add support for step min and max props

---

packages/tab/Tab.svelte

`@smui/tab` component is built over a `button` tag. The problem is that tabs can be used to navigate inside the app. With Sapper, navigation is easier using `href` instead of `goto` method, and more over, anchors support `rel="prefetch"` which allows Sapper to prefetch the page as soon as the user hovers the tab. The UX is much better and the app is snappier.
So the goal of this PR is simply replacing then `button` tag by an `anchor`.
Thanks and keep up the good work

Use anchor instead of button

---

README.md

An update to the README instructions to using svelte-material-ui with Sapper:
As used in the very same site demo, the PostCSS `extract` configuration is set to `false` and with that Sapper with Svelte works like a charm. It also sets `emitCss` to `false` and adds `css` to `true` for the Sapper client section.
Thank  you very much for smui, it’s really really cool.
All the bests for you and your projects, specially Tunnelgram.
NOTE: this is related to error https://github.com/hperrin/svelte-material-ui/issues/172

Fixing PostCSS extract configuration to prevent a Sapper fatal error

---

packages/select/Select.svelte

Fixes the issue where `MDCSelect:change` event was not triggering for the `Select` component.

(bugfix): Forward MDCSelect:change event

---

THEMING.md

I noticed when implementing the switchTheme method, that it kept adding link elements at the bottom of the head, even though there is a themeLink check. Fixed it by just also setting the id when a new link element must be created to switch the theme.

Fixed switchTheme so it doesn't keeps adding links

---

site/src/routes/demo/tabs/index.svelte

Fixed the following CSS selector on line 59: 
```css
section > :globa(div) {}
```
to
```css
section > :global(div) {}
```

Fixed css selector :globa to :global 

---

packages/form-field/README.md

The Form Fields docs link is currently pointing at the Radio Button docs, so pointed it to the right one. :)

docs: Update Form Field docs link

---

packages/common/src/classadder/classAdderBuilder.ts

Hi @hperrin, hope you're well!
I wanted to re-submit #372 (original issue #415) as it was closed and I am not able to see why it was closed/who closed it.
This error is causing my `svelte-check` task to fail with the following error:
```
$ npm run check
> datagrid@0.0.1 check
> svelte-check --tsconfig ./tsconfig.json
====================================
Loading svelte-check in workspace: /Users/jcalabro/go/src/git.cogolo.net/jcalabro/datagrid.git/ui
Getting Svelte diagnostics...
/Users/jcalabro/go/src/git.cogolo.net/jcalabro/datagrid.git/ui/node_modules/@smui/common/src/classadder/classAdderBuilder.ts:12:10
Error: Conversion of type 'typeof ClassAdder__SvelteComponent_' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert …
```

Fix Class Adder Type Overlap tsc Error

---

packages/tab-bar/src/TabBar.svelte
packages/tab-bar/src/TabBar.types.ts

I've added generic definition for the tab declaration elements. (see [Svelte Generics](https://github.com/dummdidumm/rfcs/blob/ts-typedefs-within-svelte-components/text/ts-typing-props-slots-events.md))
This makes the development experice a bit nicer since it warns you when for eg. `tabs` and `active` are not the same type.
Also the nested `tab` property gives you intellisense when accessing object properties.
**Note**: this *might* be a typechecking breaking change. But this should only happen if the code before wasn't type-correct already but suppessed by the `any` type of the `tab` variable.
Let me know if there's anything you don't like, I should change, or are generally not interested in this feature.

feat: Added strong typing for TabBar component

---

packages/menu-surface/src/MenuSurface.svelte

Change `internalStyles.maxHeight` to `internalStyles["max-height"]` in order to change the max height. Former behavior did not function.
Closes #223

fix: resolved "max height" typo in menu-surface

---

packages/accordion/src/Accordion.svelte

Change `Accordion.svelte` to verify that incoming events are from its **direct child** `Panel.svelte` (`event.target`) and _not_ from sub-children (sub-accordions).
Validation performed with _if_ statement on each of `Accordion.svelte`'s four inbound events.
Closes #436

fix: resolve issue with nested accordions not working together

---

packages/tab/src/Tab.svelte

This lets you intercept and cancel the tab change. Without this change, that was not possible. `event.preventDefault()` had no effect.
This version supersedes #411 and seems like it would be preferred over adding a new prop.
What I needed this for was to show a confirm dialog "Are you sure you want to switch tabs without saving?" and let them cancel it to stay on the current tab.
```js
...
<TabBar tabs={validTabs} let:tab bind:active>
<Tab {tab} confirm={confirmTabChange}>
<Label>{tab}</Label>
</Tab>
</TabBar>
...
<script type="ts">
function handleTabClick(event) {
if (!dirty) return
if (
!confirm('Are you sure you want to switch tabs without saving? Unsaved changes will be lost.')
) {
event.preventDefault()
}
}
</script>
```
This only works because the outer component's `on:click` …

feat: cancel tab click if event.defaultPrevented

---

packages/banner/src/Banner.svelte

Without that, the FocusTrap complains it has no focusable child (which it won't have if the user decides to not include the "actions" slot).

Allow banners to have no action buttons

---

packages/autocomplete/src/Autocomplete.svelte
packages/menu/src/Menu.svelte

Hi!
I have added a new prop to Autocomplete, it allows for the component to act as a field to append elements to a list. Her's a link with a minimal demo:
https://streamable.com/0vwsjo
It satisfies my use case, and maybe it's also useful for the community, hence the pull request. Initialy I tried to do it all inside the `$: if (!combobox && previousValue !== value)` block but text got overwritten after that, so I ended up setting text in the `$: if (previousText !== text)` block.
I hope you like it and thank you for this nice library

Add resetTextWhenSelected to Autocomplete

---

packages/textfield/src/Input.svelte

i'm not sure why it was creating a `new Number` and setting a `length` property on it. my understanding is that the primitive wrapper objects (`Number`, `String`, etc.) should be avoided.
in my case it was causing problems in my code because i was using `typeof value === 'number'` to check if a value was a number, when it was actually an `'object'`

Fix `NaN` in `toNumber`

---

.prettierignore

Since `npm run format` is **mandatory** before git lets you make a commit, it shouldn't take long to run. The `.prettierignore` file is out of date, leading to the auto-generated css files inside `packages/site/static` and `/packages/svelte-material-ui/themes` being included in the format list. And since the css files are very large, it takes a very long time for each file, leading to an infuriating wait time before the linting completes and you're finally allowed to commit a change.

fix: prettier format extremely slow because autogenerated css not excluded

---

packages/textfield/src/Textfield.svelte

This PR originates from me spending about an hour debugging the inexplicable error `Uncaught (in promise) Error: SMUI Textfield initialized without Input component`. Turns out, I didn't initalize the `value`, i.e. I did this:
```svelte
<Textfield bind:value />
<script lang="ts">
import Textfield from '@smui/textfield';
let value;
</script>
```
With this change, the error message more clearly points people to the cause of the issue.

refactor: improved error messsage when Textfield is initialized incorrectly
